### ISSUE TITLE
502 Error crashes uploader

### ISSUE THREAD

**Issue by sidequestboy** [jaymoulin/google-music-manager#10]
I'm trying to use the uploader to upload my music library, and it works for a while, the most tedious points being transcoding AACs to MP3s it seems. However, after running fine for a while, I get a server response of 502 with a whole lot of hex codes printed to my terminal, with an HTML page saying, "Server Error, please try reconnecting in 30 seconds, that's all we know". At which point `google-music-upload` has crashed.

So, I start the program again, and it zips through my mp3 320 files fast enough because google recognizes the hashes, and sends an "already exists" response, but it chokes on needing to re-transcode all my AAC files and some of my MP3 files, just to have google send more "ALREADY_EXISTS" responses.

It would be great if receiving that 502 didn't crash the program, or it could remember its place on subsequent invocations.

**Comment by jaymoulin** [comment]
Could you please send your log file?

**Comment by sidequestboy** [comment]
This is the tail end of the output, my tmux session saves 1000 lines, but the rest of the 1000 lines are more hex codes above this.

https://hastebin.com/upexometuq

Is there a more helpful log file somewhere that I don't know about?

![2018-06-26-1530033979_1366x768](https://user-images.githubusercontent.com/1538657/41928935-9d4a7af0-792b-11e8-95b0-22d4f4cc9d35.png)

**Comment by jaymoulin** [comment]
This is not what I expect to see. You should see a Debug trace on what happened and where in the code. The hex codes are just your files encrypted when sent to Google's server. More something like this : 
```
2018-06-26 19:15:21,764 - gmusicapi.Musicmanager1 (musicmanager:477) [ERROR]: problem gathering local info of ''/media/library/Make My Day - The Awakening EP (2018)/cover.jpg''
Traceback (most recent call last):
   File "/usr/local/lib/python3.6/site-packages/gmusicapi/clients/musicmanager.py", line 475, in upload
     track = musicmanager.UploadMetadata.fill_track_info(path)
   File "/usr/local/lib/python3.6/site-packages/gmusicapi/protocol/musicmanager.py", line 216, in fill_track_info
     track.client_id = cls.get_track_clientid(filepath)
   File "/usr/local/lib/python3.6/site-packages/gmusicapi/protocol/musicmanager.py", line 177, in get_track_clientid
     audio.delete()
 AttributeError: 'NoneType' object has no attribute 'delete'
```

**Comment by sidequestboy** [comment]
Unfortunately the stack trace is pushed out of my tmux history... and it
takes running the program for many hours for the crash to show up.

**Comment by sidequestboy** [comment]
FWIW, I surrounded https://github.com/jaymoulin/google-music-manager/blob/27674e102a2facd0bbbac7af0b6b7db986b8417d/uploader/google_music_manager_uploader/uploader_daemon.py#L48 with a try/except with a 30 second wait in the except block, and now the program hasn't crashed in almost two days (running on a raspberry pi, it seems to be doing a LOT of ffmpeg transcoding)

**Comment by jaymoulin** [comment]
As you can see that already was my guess. But you can't catch all exceptions and treat them the way you did, that's why I needed and still need, the log file

https://github.com/jaymoulin/google-music-manager/blob/feature-12/uploader/google_music_manager_uploader/uploader_daemon.py

P.S: it does a lot of ffmpeg transcoding because of Google Music limitations (files must be MP3 encoded) and your library isn't. You can speed up the process by giving MP3 files to google-music-manager and avoid on-the-fly transcoding

**Comment by sidequestboy** [comment]
Oh cool, I wasn't following your commits. Yes, definitely. Should I run the
current master commit to test it out? Would stderr be cleaner than the
terminal output I guess?

**Comment by jaymoulin** [comment]
You can try to run with the `feature-12` branch and display the stderr as well to check if this feature fits your needs. I didn't have time to test it yet, that's the reason it's not in the master yet. Anyway, this feature would have taken less much time with a proper log file to rely on.
