### ISSUE TITLE
Constant library scanning

### ISSUE THREAD

**Issue by rix1337** [jaymoulin/google-music-manager#12]
I have successfully uploaded my library to GPM using this tool. Thanks for that.

If I look at my disk spinups, however, I see my HDD housing the music library constantly spinning.
Using `lsof /music/library/path` I can see ffmpeg constantly accessing mp3s that were already uploaded.

Is this working as intended? If yes, please add the ability to remember what you changed before.. (as in: only scan dirs for upload, that have changed in some way.)

**Comment by jaymoulin** [comment]
This working as intended. You have a remove function to get rid of your uploaded file.
There is so many ways to handle this behaviour so, what are your suggestions and can't you do PR for that?

**Comment by rix1337** [comment]
Okay, so these are my obversations:
Your docker image starts the upload daemon https://gitlab.com/jaymoulin/docker-google-musicmanager/blob/master/daemon.sh#L27 directing it towards a folder

You are using watchdog within the uploader to monitor the file system (which is great!), which will not remember the current state after a restart.. correct?

Delete mode is not an option for me, thats why I would love to save that watchdog state.

I will try this myself. Would you accept a PR if I get it working?

**Comment by jaymoulin** [comment]
Sure, I'll be glad to review your PR!

**Comment by rix1337** [comment]
I will instead support the original gm manager in docker.
