### ISSUE TITLE
google-musicmanager container errors starting downloader

### ISSUE THREAD

**Issue by dustinmhorvath** [jaymoulin/google-music-manager#14]
Reporting this here for the container at https://hub.docker.com/r/jaymoulin/google-musicmanager/.

Attempting to start the docker container while supplying an uploader_id environment variable produces the following error:

```
usage: google-music-download [-h] [--directory DIRECTORY] [--oauth OAUTH]
                             [--device_id DEVICE_ID]
google-music-download: error: unrecognized arguments: --uploader_id [redacted mac with colons and all uppercase]
```

If the uploader_id is *not* provided, then the error states 

```
google-music-download: error: unrecognized arguments: --uploader_id false
```

The uploader seems to function correctly, but the downloader seems like it's still attempting to handle a deprecated variable (for the downloader).

**Comment by jaymoulin** [comment]
This is not the repo you are looking for

The repo you are looking for is: https://github.com/jaymoulin/docker-google-musicmanager therefore https://gitlab.com/jaymoulin/docker-google-musicmanager therefore https://gitlab.com/jaymoulin/docker-google-musicmanager/issues/11

I was not able to reproduce your issue without your parameters BUT I was able to find a possible issue with optional parameters.

Please provide me more informations so I may be able to help.
