### ISSUE TITLE
Remove Mp3 AlbumCover?

### ISSUE THREAD

**Issue by liante0904** [jaymoulin/google-music-manager#16]
When I upload my Music in Synology, I check to disappear mp3 album cover.
Is it right?

**Comment by jaymoulin** [comment]
I don't understand your issue. Could you clarify?

**Comment by liante0904** [comment]
Which aspect is not clear? Album cover? If not.. my testing system?

**Comment by liante0904** [comment]
![57515FBC-BBD3-476F-95F9-4BD694EDE7C4](https://user-images.githubusercontent.com/17792485/59160819-5f3e4000-8b15-11e9-82ce-ede14adfa229.png)
The songs uploaded through this app. 
The original file has a cover image, but the image is gone after uploading.

**Comment by jaymoulin** [comment]
Nothing is clear for me. 
- What is your process?
- What are you trying to perform?
- From where? To where?
- What are you checking?
- What is the expected result?

**Comment by jaymoulin** [comment]
OK I understand. 
This is a known issue of the library I'm using: https://github.com/simon-weber/gmusicapi/issues/242
Nothing is planned on fixing this yet

**Comment by liante0904** [comment]
oh.. I see. When I opening issue, I don't check that.
Thanks for your feedback. Have a nice day. :)

**Comment by jaymoulin** [comment]
Thanks for your report, some contributors may eventually propose something for this

**Comment by jaymoulin** [comment]
Should be fixed by https://github.com/jaymoulin/google-music-manager-uploader/commit/f1037eb9e47a59115985bcdd008aef8d28ac193f

**Comment by jaymoulin** [comment]
Not fixed because of https://github.com/simon-weber/gmusicapi/issues/420 not working anymore

**Comment by jaymoulin** [comment]
Fixed by https://github.com/jaymoulin/google-music-manager-uploader/releases/tag/1.5.4
