### ISSUE TITLE
Switch to yt music?

### ISSUE THREAD

**Issue by gartkb** [jaymoulin/google-music-manager#17]
Hi Jay. Since google music is going away, I wonder if you would consider adapting your very useful project here to you tube music?  I saw this: https://github.com/sigma67/ytmusicapi/releases

**Comment by jaymoulin** [comment]
Thank you for your suggestion!

For the moment, Youtube Music is not available in my country and, when it will, I will need to allow me some time to work on this project. Thank you for giving me tools so I can check where to begin ;)

I'm glad you like my products and you may want to support my work for maintaining and evolving them with donation on those platforms [![PayPal donation](https://github.com/jaymoulin/jaymoulin.github.io/raw/master/ppl.png "PayPal donation")](https://www.paypal.me/jaymoulin) [![Buy me a coffee](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png "Buy me a coffee")](https://www.buymeacoffee.com/3Yu8ajd7W) [![Become a Patron](https://badgen.net/badge/become/a%20patron/F96854 "Become a Patron")](https://patreon.com/jaymoulin).

**Comment by jaymoulin** [comment]
I had to create another package for dependencies are not maintained anymore.

https://github.com/jaymoulin/youtube-music-uploader
