### ISSUE TITLE
Local files being deleted even with False as attribute

### ISSUE THREAD

**Issue by jameshope87** [jaymoulin/google-music-manager#3]
So I ran the command like so:

    screen -dmS music sudo python3.6 /home/pi/google-music-manager/uploader-daemon.py /home/pi/google-music-manager/musiclibrary /root/oauth False

Expecting the files on my pc to remain, however they have still been deleted.

Please can you look into this?

Thanks

**Comment by jameshope87** [comment]
Checked out the code. Discovered that if anything is put in that 3rd argument then it delete the files.

Putting only 2 arguments fixes the issue. However the readme is misleading.

**Comment by jaymoulin** [comment]
Thanks for your report, you're right I have to handle that. I should fix in the code AND the documentation since nothing matches what I wanted. The third parameter should be changeable.

**Comment by jameshope87** [comment]
I can see your potential problem though. If someone enters something other than a Boolean then it will case issues.

Loving the functionality so far though. I am having a potential other issue. With a large music collection it seems to crash after a few albums uploaded.

I will upload some logs and open another issue if you would like?

**Comment by jaymoulin** [comment]
I always love contributions. Logs, issue, bug report, bug fixes, pull request... everything is welcomed
