### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '~/oauth'

### ISSUE THREAD

**Issue by seantdavidson** [jaymoulin/google-music-manager#5]
Unless I missed something I can't seem to get the Authorization of Google Music running this on my Raspberry Pi 3 running Rasbian Stretch.

**Comment by jaymoulin** [comment]
Could you please give some details on what you did?

**Comment by seantdavidson** [comment]
As for details, I ran the following.
```
apt-get install python3-pip libav-tools build-essential
pip3 install watchdog gmusicapi bs4 netifaces
```

Then I ran the following
`google-music-auth`

It took me to the URL for auth and then gave me a link with a code.
Then I tried running the following to test upload.
`google-music-upload`

And got the error.

**Comment by jaymoulin** [comment]
I think some informations are missing in your details... could you please be very detailed on ALL your steps of installation and usage.

Also, could you assure that a file named `oauth` is present and accessible in your home folder please?

**Comment by seantdavidson** [comment]
Jay thanks, I added the file manually and that worked. Sorry I thought it would be added when I did the authentication.

**Comment by jaymoulin** [comment]
Your authentication probably failed as well and that's why I released a bugfix
