### ISSUE TITLE
simplify acquisition of the default network interface

### ISSUE THREAD

**Issue by klokie** [jaymoulin/google-music-manager#7]
Hi again :)
I think this project looks amazing!
I wonder, being a Python newbie, if there's an easy way to abstract the custom `uploader_id` functionality? I see that the default net interface specified in [uploader_daemon.py](https://github.com/jaymoulin/google-music-manager/blob/c2a48ad44825a33e02bb38087b29f85b50dbda29/uploader/google_music_manager_uploader/uploader_daemon.py#L32) is `eth0`, but on a Mac I think this should be `en0`. I was thus able to get the appropriate MAC by running the following:

```
$ python3.6
Python 3.6.4 (default, Mar  9 2018, 23:15:12)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import netifaces
>>> netifaces.ifaddresses('en0')[netifaces.AF_LINK][0]['addr'].upper()
'AA:BB:CC:DD:EE:FF'
```

**Comment by jaymoulin** [comment]
If I do this update, I will break for linux and windows users. If you can PR something that can be compatible for all of them, I'll merge it.

**Comment by jaymoulin** [comment]
Anyway I'll see what I can do
